### ISSUE TITLE
Use extract-zip instead of decompress-zip

### ISSUE THREAD

**Issue by develar** [electron/node-mksnapshot#3]
* not maintained anymore (https://github.com/bower/decompress-zip/pull/53)
* extract-zip has less dependencies.

What do you think? I can prepare pull request if you don't mind.

It is important for me since asar uses mksnapshot.

**Comment by lee-dohm** [comment]
Is there something broken in decompress-zip? Something it isn't doing that it should?

**Comment by develar** [comment]
My concern is only mentioned https://github.com/bower/decompress-zip/pull/53

electron-builder uses electron-packager,
electron-packager uses asar, 
asar uses mksnapshot,
mksnapshot uses decompress-zip

decompress-zip maintainers don't publish new version and ignore PR https://github.com/bower/decompress-zip/pull/53

As result, users of electron-packager/electron-builder get warning "graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible." (and increased number of node dependencies).

**Comment by ahgan84** [comment]
Yes. I encounter this problem also whereby I will get the warnning "graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible." (and increased number of node dependencies)"

When I type "npm run pack" I got an error saying:
C:\node_modules\electron-builder\out\build-cli.js:5
const builder_1 = require("./builder");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Does this error related to the graceful-fs not update?

**Comment by develar** [comment]
@ahgan84 Your issue is different, please ensure that you use NodeJS version 4+.

**Comment by ppitonak** [comment]
Since https://github.com/bower/decompress-zip/pull/53 was merged, can you please upgrade to decompress-zip 0.3.0?

**Comment by kevinsawicki** [comment]
Fixed by #4
